name: Nightly Ceremony

on:
  schedule:
    - cron: 0 0 * * *

env:
  STATE_TREE_DEPTH: ${{ vars.STATE_TREE_DEPTH }}

jobs:
  test-with-ceremony-keys:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --yes \
            build-essential \
            libgmp-dev \
            libsodium-dev \
            nasm \
            nlohmann-json3-dev

      - name: Install
        run: |
          pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: |
          pnpm run build

      - name: Run hardhat fork
        run: |
          cd contracts
          pnpm run hardhat &

      - name: Download rapidsnark (1c137)
        run: |
          mkdir -p ~/rapidsnark/build
          wget -qO ~/rapidsnark/build/prover https://maci-devops-zkeys.s3.ap-northeast-2.amazonaws.com/rapidsnark-linux-amd64-1c137
          chmod +x ~/rapidsnark/build/prover

      - name: Download ceremony artifacts
        run: ./.github/scripts/download-ceremony-artifacts.sh

      - name: Run e2e tests
        run: pnpm test:cli-ceremony

      - name: Stop Hardhat
        if: always()
        run: kill $(lsof -t -i:8545)
